// models/Symptom.js

const mongoose = require('mongoose');

const SymptomSchema = new mongoose.Schema({
  High_Fever: { type: Number, enum: [0, 1], required: true, default: 0 },
  Severe_Headache: { type: Number, enum: [0, 1], required: true, default: 0 },
  Pain_Behind_Eyes: { type: Number, enum: [0, 1], required: true, default: 0 },
  Muscle_and_Joint_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Skin_Rash: { type: Number, enum: [0, 1], required: true, default: 0 },
  Nausea_and_Vomiting: { type: Number, enum: [0, 1], required: true, default: 0 },
  Fatigue: { type: Number, enum: [0, 1], required: true, default: 0 },
  Mild_Bleeding: { type: Number, enum: [0, 1], required: true, default: 0 },
  Abdominal_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Redness_in_Palms_and_Soles: { type: Number, enum: [0, 1], required: true, default: 0 },
  Cyclical_Fever_with_Chills_and_Sweating: { type: Number, enum: [0, 1], required: true, default: 0 },
  Muscle_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Diarrhea: { type: Number, enum: [0, 1], required: true, default: 0 },
  Jaundice: { type: Number, enum: [0, 1], required: true, default: 0 },
  Confusion_or_Altered_Mental_State: { type: Number, enum: [0, 1], required: true, default: 0 },
  Sudden_Onset_of_Fever: { type: Number, enum: [0, 1], required: true, default: 0 },
  Debilitating_Joint_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Rash: { type: Number, enum: [0, 1], required: true, default: 0 },
  Mild_Headache: { type: Number, enum: [0, 1], required: true, default: 0 },
  Nausea: { type: Number, enum: [0, 1], required: true, default: 0 },
  Swelling_in_Joints: { type: Number, enum: [0, 1], required: true, default: 0 },
  Muscle_Tenderness: { type: Number, enum: [0, 1], required: true, default: 0 },
  Eschar: { type: Number, enum: [0, 1], required: true, default: 0 },
  Chills: { type: Number, enum: [0, 1], required: true, default: 0 },
  Lymph_Node_Swelling: { type: Number, enum: [0, 1], required: true, default: 0 },
  Dry_Cough: { type: Number, enum: [0, 1], required: true, default: 0 },
  Hearing_Loss: { type: Number, enum: [0, 1], required: true, default: 0 },
  Stiff_Neck: { type: Number, enum: [0, 1], required: true, default: 0 },
  Seizures: { type: Number, enum: [0, 1], required: true, default: 0 },
  Altered_Mental_Status: { type: Number, enum: [0, 1], required: true, default: 0 },
  Vomiting: { type: Number, enum: [0, 1], required: true, default: 0 },
  Tremors: { type: Number, enum: [0, 1], required: true, default: 0 },
  Paralysis_or_Muscle_Weakness: { type: Number, enum: [0, 1], required: true, default: 0 },
  Speech_Difficulties: { type: Number, enum: [0, 1], required: true, default: 0 },
  Sensitivity_to_Light: { type: Number, enum: [0, 1], required: true, default: 0 },
  Sudden_Fever: { type: Number, enum: [0, 1], required: true, default: 0 },
  Convulsions: { type: Number, enum: [0, 1], required: true, default: 0 },
  Confusion: { type: Number, enum: [0, 1], required: true, default: 0 },
  Coma: { type: Number, enum: [0, 1], required: true, default: 0 },
  Muscle_Weakness: { type: Number, enum: [0, 1], required: true, default: 0 },
  Difficulty_Swallowing: { type: Number, enum: [0, 1], required: true, default: 0 },
  Hallucinations: { type: Number, enum: [0, 1], required: true, default: 0 },
  Loss_of_Appetite: { type: Number, enum: [0, 1], required: true, default: 0 },
  Respiratory_Distress: { type: Number, enum: [0, 1], required: true, default: 0 },
  Fever: { type: Number, enum: [0, 1], required: true, default: 0 },
  Neurological_Symptoms: { type: Number, enum: [0, 1], required: true, default: 0 },
  Swollen_Lymph_Nodes: { type: Number, enum: [0, 1], required: true, default: 0 },
  Eye_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Joint_Stiffness: { type: Number, enum: [0, 1], required: true, default: 0 },
  High_Fever_with_Chills: { type: Number, enum: [0, 1], required: true, default: 0 },
  Bleeding_Tendencies: { type: Number, enum: [0, 1], required: true, default: 0 },
  Pain_in_the_Abdomen: { type: Number, enum: [0, 1], required: true, default: 0 },
  Low_Blood_Pressure: { type: Number, enum: [0, 1], required: true, default: 0 },
  Back_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Brain_Inflammation: { type: Number, enum: [0, 1], required: true, default: 0 },
  Drowsiness: { type: Number, enum: [0, 1], required: true, default: 0 },
  Muscle_Aches: { type: Number, enum: [0, 1], required: true, default: 0 },
  Double_Vision: { type: Number, enum: [0, 1], required: true, default: 0 },
  Weakness_or_Paralysis: { type: Number, enum: [0, 1], required: true, default: 0 },
  Rapid_Breathing: { type: Number, enum: [0, 1], required: true, default: 0 },
  Persistent_Cough: { type: Number, enum: [0, 1], required: true, default: 0 },
  Sore_Throat: { type: Number, enum: [0, 1], required: true, default: 0 },
  Body_Aches: { type: Number, enum: [0, 1], required: true, default: 0 },
  Runny_or_Stuffy_Nose: { type: Number, enum: [0, 1], required: true, default: 0 },
  Shortness_of_Breath: { type: Number, enum: [0, 1], required: true, default: 0 },
  Chest_Pain: { type: Number, enum: [0, 1], required: true, default: 0 },
  Puffy_Cheeks: { type: Number, enum: [0, 1], required: true, default: 0 },
  Swollen_Jaw: { type: Number, enum: [0, 1], required: true, default: 0 },
  Pain_while_Chewing_or_Swallowing: { type: Number, enum: [0, 1], required: true, default: 0 },
  Headache: { type: Number, enum: [0, 1], required: true, default: 0 },
  Swelling_in_Other_Glands: { type: Number, enum: [0, 1], required: true, default: 0 }
}, { timestamps: true });

module.exports = mongoose.model('Symptom', SymptomSchema);
